In [2]:
import numpy as np
import sys

The basics

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#how to get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#how to get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
#how to get type
print(a.dtype)

int32


In [8]:
#how to get size
print(a.size)
print(b.size)

3
6


In [9]:
#how to get number of bytes
print(a.itemsize)
print(b.itemsize)

4
4


In [10]:
#how to get total size
print(a.nbytes)
print(b.nbytes)

12
24


In [11]:
c=np.array([[3,2,3,4,5,6,7,8,9,0],[8,5,9,6,3,4,5,7,0,1]])
c

array([[3, 2, 3, 4, 5, 6, 7, 8, 9, 0],
       [8, 5, 9, 6, 3, 4, 5, 7, 0, 1]])

In [12]:
#get specific element (row, col)
c[1,1]

5

In [13]:
#get specific row
c[0,:]

array([3, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [14]:
#get specific column

c[:,2]

array([3, 9])

In [15]:
#Getting a little fancy [startindex:endindex:stepsize]
c[0, 1:6:1]

array([2, 3, 4, 5, 6])

In [16]:
#3d array
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
d[0,1,1]

4

In [18]:
d[:,1,:0]

array([], shape=(2, 0), dtype=int32)

Initializing different type of arrays

In [19]:
#all zeroes
z=np.zeros([5,9])
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# all ones matrix
o=np.ones([2,3,3])
o

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
# all (specific number) matrix

m= np.full([3,3],99)
m

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [22]:
#full arrays like another existing array

lk=np.full_like(m,88)
lk

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [23]:
#ranodm number full arrays
rnd=np.random.rand(4,2,3)
rnd

array([[[0.12173324, 0.66667082, 0.3926975 ],
        [0.47077633, 0.51981282, 0.27389911]],

       [[0.32436462, 0.65258265, 0.29035415],
        [0.75813591, 0.06183208, 0.78614437]],

       [[0.78705598, 0.88052465, 0.23531325],
        [0.38752465, 0.37660077, 0.16989867]],

       [[0.07563229, 0.4708698 , 0.83419346],
        [0.66507618, 0.40451544, 0.74693471]]])

In [24]:
#random full arrays like another existing array
rnd_lk=np.random.random_sample(m.shape)
rnd_lk

array([[0.32702489, 0.32372587, 0.73644334],
       [0.46062135, 0.56490882, 0.82898997],
       [0.48883588, 0.65155221, 0.30924107]])

In [25]:
#random full array with values lower than 7
np.random.randint(7, size=(3,3))

array([[3, 6, 0],
       [6, 5, 3],
       [5, 6, 4]])

In [26]:
#random full array within -4 to 7
np.random.randint(-4,7, size=(3,3))

array([[ 6, -3, -2],
       [ 3, -3, -1],
       [ 1,  2,  2]])

In [27]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#repeating values 3 times
arr=np.array([1,2,3])
rp=np.repeat(arr,3)
rp

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [29]:
#repeating an array 3 times
arr1=np.array([[1,2,3]])
rp=np.repeat(arr1,3,axis=0)
rp

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
output=np.ones((5,5))
output
replace=np.zeros((3,3))
print(replace)
replace[1,1]=9
output [1:4,1:4] =replace
output

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Be careful while copying arrays!!!!

In [31]:
a=np.array([1,2,3])
print(a)
b=a
print(b)
b[0]=100
print(b)
print(a)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


## changed the value of b but the values of  a also got changed

b=a does not mean a new copy of a has been created at the location of b. It means b and a points to the same location.
To cretae a new copy, a.copy() has to be used

In [32]:
a=np.array([1,2,3])
print(a)
b=a.copy()
print(b)
b[0]=100
print(b)
print(a)

[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]


# Mathmatics

In [33]:
a+2

array([3, 4, 5])

In [34]:
a-2

array([-1,  0,  1])

In [35]:
a*2

array([2, 4, 6])

In [36]:
a/2

array([0.5, 1. , 1.5])

In [37]:

b=np.array([3,4,5])
a+b

array([4, 6, 8])

In [38]:
#sin of all values
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [39]:
#power 2
a**2

array([1, 4, 9], dtype=int32)

# Linear Algebra

In [40]:
#matrix multiplication
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [41]:
#determinant of a mtatrix
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [42]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.min(stats)

1

In [44]:
np.mean(stats)

3.5

In [45]:
#min and mean of rows
print(np.min(stats, axis=1))
print(np.mean(stats, axis=1))

[1 4]
[2. 5.]


In [46]:
#min and mean of columns
print(np.min(stats, axis=0))
print(np.mean(stats, axis=0))

[1 2 3]
[2.5 3.5 4.5]


# rearranging array

In [47]:
before=np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [50]:
after=before.reshape((6,1))
print(after)
after=before.reshape((3,2))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


In [51]:
#vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [55]:
# stacking horizontally
h1=np.ones((2,2))
h2=np.zeros((2,3))
np.hstack([h2,h1])

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

# Miscelleneous

Load data

In [58]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)
filedata= filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced indexing

In [59]:
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [65]:
(filedata >50) & (filedata <150)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [66]:
(~(filedata >50) & (filedata <150))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [60]:
filedata[filedata >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [64]:
#indexing list
a=np.array([3,4,5,6,7,8,9])
a[[2,3,6]]

array([5, 6, 9])